name: Bug Report
description: Report a bug or an issue in the game.
labels: ["type: minor bug", "status: pending triage"]
title: "Bug Report: "
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: I have properly named the issue
        - label: I have checked the issues/discussions pages to see if the issue has been previously reported

  - type: input
    attributes:
      label: Linux Distribution
      description: Which Linux distribution are you using?
      placeholder: ex. Pop!_OS, Ubuntu/Debian, Arch (btw)...
    validations:
      required: true
      
  - type: input
    attributes:
      label: Version
      description: What version are you using?
      placeholder: ex. 0.4.1
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Describe your bug."

  - type: markdown
    attributes:
      value: |
        ### Please do not report issues from other engines. These must be reported in their repositories.
        ### Also do notice that issues that are in the base game are likely to not be fixed! Only report issues specific to these builds

  - type: markdown
    attributes:
      value: "#### Provide as many details as you can."

  - type: textarea
    attributes:
      label: Context (Provide images, videos, etc.)

  - type: textarea
    attributes:
      label: Steps to reproduce (or crash logs, errors, etc.)
