name: Corrupt Attachment Report
description: Report an issue with the release attachments.
labels: ["type: repository", "status: pending triage"]
title: "Corrupt Attachment Report: "
body:
  - type: markdown
    attributes:
      value: "#### Please check for duplicates before opening an issue."
      
  - type: checkboxes
    attributes:
      label: Issue Checklist
      description: Be sure to complete these steps to increase the chances of your issue being addressed!
      options:
        - label: I have checked the Issues/Discussions pages to see if my issue has already been reported
        - label: I have properly titled my issue

  - type: input
    attributes:
      label: Release Version
      description: Which version were you trying to download?
      placeholder: ex. 0.5.3
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Describe the problem."

  - type: markdown
    attributes:
      value: |
        ### Please do not report issues from other engines. These must be reported in their repositories.
        ### Also do notice that issues that are in the base game are likely to not be fixed! Only report issues specific to these builds.

  - type: textarea
    attributes:
      label: Description
      description: Provide as much detail as you can. The better others understand your issue, the more they can help you!
      placeholder: Describe your issue here...
    validations:
      required: true
