# Credits to tposejank for the templates!
name: Crash Report
description: Report a crash that occurred while playing the game.
labels: ["type: major bug", "status: pending triage"]
title: "Crash Report: "
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: I have properly named the issue
        - label: I have checked the issues/discussions pages to see if the issue has been previously reported

  - type: input
    attributes:
      label: Linux Distribution
      description: Which Linux distribution are you using?
      placeholder: ex. Pop!_OS, Ubuntu/Debian, Arch (btw)...
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: What version are you using?
      placeholder: ex. 0.4.1
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Describe your issue."

  - type: markdown
    attributes:
      value: |
        ### Please do not report issues from other engines. These must be reported in their repositories.
        Do also notice that issues also in the base game are likely to not be fixed in these builds!

  - type: markdown
    attributes:
      value: "#### Provide as many details as you can."

  - type: textarea
    attributes:
      label: Context (Provide screenshots or videos of the crash happening)

  - type: textarea
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Crash logs (can be found in the logs folder where Funkin's executable is)"
    validations:
      required: true
